name: Atualizar index.html automático

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Baixar novo index.html diretamente do ChatGPT
        run: curl -o index.html "https://chatgpt-static.s3.amazonaws.com/chronic/67fbafa7-57f0-8191-95bb-2ebde46e0607/index.html"

      - name: Commitar nova versão
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "Checklist Bot"
          git config --global user.email "bot@checklist.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/vscompanyuba/checklist-davi.git
          git add index.html
          git commit -m "Atualização automática do checklist"
          git push origin main
