name: Atualizar index.html automático

on:
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # impede que o checkout use as credenciais padrão

      - name: Baixar novo index.html do ChatGPT
        run: curl -o index.html https://raw.githubusercontent.com/davidsmonteiro/chatgpt-checklist-index/main/index.html

      - name: Commitar nova versão
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "Checklist Bot"
          git config --global user.email "bot@checklist.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/vscompanyuba/checklist-davi.git
          git add index.html
          git commit -m "Atualização automática do checklist" || echo "Nada para commitar"
          git push origin main
